# Environment configuration
environment: "dev"  # Environment (e.g., dev, stag, prod)

# Service configuration
service_config:
  name: auth-service  # Name of the service
  port: 8080          # Port on which the service runs
  timeout: 10         # Request timeout in seconds
  retries: 3          # Number of retries on failure

# Database configuration
database_config:
  postgres_config:
    postgres_uri: "POSTGRES_URI"           # URI for PostgreSQL database
    max_idle_connections: 2               # Max Idle Connections
    max_open_connections: 20              # Max Open Connections
    connection_timeout: 30                 # Connection timeout in seconds
    idle_timeout: 300                      # Idle timeout in seconds
    conn_max_lifetime: 3600                # Maximum amount of time a connection may be reused
    conn_max_idle_time: 600                # Maximum amount of time a connection may be idle
    prefer_simple_protocol: true           # Prefer simple protocol
  redis_config:
    redis_uri: "REDIS_URI"                 # URI for Redis database
    max_idle_connections: 2               # Max Idle Connections
    max_active_connections: 20            # Max Active Connections
    idle_timeout: 300                      # Idle timeout in seconds
    wait: true                             # Wait for a connection to be available

# Logging configuration
logging_config:
  level: "info"  # Logging level (e.g., info, debug)